version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nemi
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - 'db_data:/var/lib/mysql'

volumes:
  db_data: